// Mocks generated by Mockito 5.2.0 from annotations
// in barcode_scanner/test/modules/domain/usecases/create_scanned_code_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:barcode_scanner/modules/code_scanner/domain/entities/scanned_code.dart'
    as _i4;
import 'package:barcode_scanner/modules/code_scanner/domain/repositories/create_scanned_code_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [CreateScannedCodeRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCreateScannedCodeRepository extends _i1.Mock
    implements _i2.CreateScannedCodeRepository {
  MockCreateScannedCodeRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<dynamic> create(_i4.ScannedCode? scannedCode) =>
      (super.noSuchMethod(Invocation.method(#create, [scannedCode]),
          returnValue: Future<dynamic>.value()) as _i3.Future<dynamic>);
}
